name: Build and deploy Node.jaes tsefo Azure Web App - react-app-service

on:
  push:
    branches:
      - react-app
  workflow_dispatch:

jobs:
  deploy:
      runs-on: window-latest
      steps:
            - name: Check Azure CLI version
              run: az --version
            - name: 'Login via Azure CLI'
              uses: azure/login@v1
              with:
                creds: '{"clientId":"${{ secrets.AZURE_CLI }}","clientSecret":"${{ secrets.AZURE_SECRET }}","tenantId":"${{ secrets.TENANT_ID }}"}'              

