name: Build and deploy Node.js to Azure Web App - react-app-service

on:
  push:
    branches:
      - react-app
  workflow_dispatch:
jobs:

  deploy:
      strategy:
        matrix:
          os: [ubuntu-latest]
      runs-on: ${{ matrix.os }}
      steps:
            - name: Check Azure CLI version
              run: az --version
            - uses: Azure/login@v1
              with:
                creds: '{"clientId":"${{ secrets.AZURE_CLI }}","clientSecret":"${{ secrets.AZURE_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
