name: Build and deploy Node.js to Azure Web App - react-app-service

on:
  push:
    branches:
      - react-app
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SECRET }}
          client-id: ${{ secrets.AZURE_CLI }}
          tenant-id: ${{ secrets.TENANT_ID }}

      - name: Check Azure CLI version
        run: az --version
