name: Build and deploy Node.jaes tsefo Azure Web App - react-app-service

on:
  push:
    branches:
      - react-app
  workflow_dispatch:

jobs:
  deploy:
      strategy:
        matrix:
          os: [windows-latest,ubuntu-latest]
      runs-on: ${{ matrix.os }}
      steps:
            - name: Check Azure CLI version
              run: az --version

